import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fursuit Detector App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id={styles.formContainer}>
        <input type="file" name="image" id='image'/>
        <input type="submit" value="Upload"/>
      </div>
    </div>
  )
}

export default Home;