import Head from 'next/head'
import { useState, useCallback } from 'react';
import { useDropzone } from 'react-dropzone'

export default function Home() {
  // const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop, accept, multiple: false })

  const onDrop = useCallback(acceptedFiles => {
    console.log(acceptedFiles)
  }, []);

  const [numberOfFurs, setNumberOfFurs] = useState(0);

  const handleSubmit = (e: any) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    
    const Upload = async() => {
      await fetch('http://127.0.0.1:5000/detect', {
        method: 'POST',
        body: formData
      }).then(resp => {
        resp.json().then(data => {
          console.log(data)
          setNumberOfFurs(data.numberOfFurs);
        })
      })
    }
    Upload();
  }

  return (
    <div>
      <Head>
        <title>Fursuit Detector App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="formContainer">
        {/* <div {...getRootProps()}>
          <div className="dropzone-input" {...getInputProps()}>
            {isDragActive ? (
              <p>Let it go, let it go</p>
            ) : (
              <p>Drop some files</p>
            )}
          </div>
        </div> */}
        <form onSubmit={handleSubmit}>
          <input type="file" name="image" id='image'/>
          <input type="submit" value="Upload"/>
        </form>
      </div>
      <p>number of furries in the image: {numberOfFurs}</p>
    </div>
  );
}